discord-webhook-url: <your-discord-webhook-url> # Insert your discord webhook string here

web-database-api:
  # The Web Address of the API that will be used to access the database
  # You will need to host this on a webserver yourself
  url: https://<your-webserver>/database.php

  # Prevents unauthorized access
  access-token: <database-access-token>

worldborder:
  # Worldborder diameter
  size: 1400

  # How far it will shrink after the shrinkdelay is over
  shrinksize: 200

  # When the border will start shrinking in minecraft ticks
  shrinkdelay: 144000

  # How long it will take to shrink to the shrinksize after the shrinkdelay in seconds
  shrinkduration: 400

autostart:
  # How many players the game needs until it starts itself
  required-players: 20

  # When the game will start after enough players joined
  seconds: 30

protection-time:
  # Whether the 10 Minutes protection time is enabled
  enabled: 1

teams:
  max-allowed-size: 2